# General configuration of the IPF application.

spring:
  application:
    name: ipf-example
server:
  # Application listening port
  port: 8080
webapp:
  api:
    # HTTP prefix of all routes
    prefix: /services/*
ipf:
  atna:
    # Disable ATNA logging as it requires more efforts to work
    # See: https://oehf.github.io/ipf-docs/docs/ihe/atna/
    audit-enabled: false
